### ISSUE TITLE
Unable to find the url?

### ISSUE THREAD

**Issue by N3evin** [MrKev312/AmiiboGameListGenerator#3]
Not too sure why, but seems like they are using naming convention for their URL?

```
https://amiibo.life/amiibo/the-legend-of-zelda/zelda-loftwing
	System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at AmiiboGameList.Program.<>c__DisplayClass3_0.<Main>b__0(KeyValuePair`2 DBamiibo) in 
   ```

**Comment by MrKev312** [comment]
Fixed in latest release!
